import { spawn, type ChildProcess } from 'node:child_process';
import { writeFileSync, appendFileSync } from 'node:fs';
import { join } from 'node:path';
import { TaskState } from './TaskState.js';
import { env } from './env.js';
import type { SpawnResult } from './Engine.js';

// ── File names ──────────────────────────────────────────────────────────────
const F_AGENT_LOG = 'agent.log';

export interface PiSpawnerOptions {
  /** Default model when task doesn't specify one */
  readonly model?: string;
  /** Fallback model if primary fails */
  readonly fallbackModel?: string;
  /** Working directory for the agent */
  readonly workDir?: string;
}

export class PiSpawner {
  readonly #model: string;
  readonly #fallback: string;
  readonly #workDir: string;

  constructor(opts: PiSpawnerOptions = {}) {
    this.#model = opts.model
      ?? env.model;
    this.#fallback = opts.fallbackModel ?? 'openrouter/owl-alpha';
    this.#workDir = opts.workDir ?? process.cwd();
  }

  /** Resolve the model for a task: metadata → constructor → env → default */
  modelFor(task: TaskState): string {
    return task.model || this.#model;
  }

  async spawn(task: TaskState, worktreePath?: string, signal?: AbortSignal): Promise<SpawnResult> {
    const cwd = worktreePath ?? this.#workDir;
    const models = [this.modelFor(task), this.#fallback]
      .filter((m, i, arr) => m && arr.indexOf(m) === i);

    console.log(`T${task.taskNumber} using ${models.join(', ')}`);
    for (const model of models) {
      /* c8 ignore next 1 */
      if (signal?.aborted) return { success: false, iterations: 0 };
      const result = await this.#run(task, model, cwd, signal);
      if (result.success) return result;
    }
    return { success: false, iterations: 0 };
  }

  #run(task: TaskState, model: string, cwd: string, signal?: AbortSignal): Promise<SpawnResult> {
    /* c8 ignore next 1 */
    if (signal?.aborted) return Promise.resolve({ success: false, iterations: 0 });

    return new Promise(resolve => {
      let settled = false;
      const done = (r: SpawnResult) => { if (!settled) { settled = true; resolve(r); } };

      const child: ChildProcess = spawn('pi', [
        '--mode', 'json',
        '--no-session',
        '--model', model,
        '-p', this.#prompt(task, cwd),
      ], {
        cwd,
        stdio: ['ignore', 'pipe', 'pipe'],
        timeout: 600_000, // 10 min
      });

      // Kill child if stop signal fires mid-spawn
      // Call done() BEFORE child.kill() to prevent a race on platforms where
      // kill() synchronously emits 'close' (which also calls done()).
      /* c8 ignore next 1 */
      signal?.addEventListener('abort', () => { done({ success: false, iterations: 0 }); child.kill(); }, { once: true });

      let output = '';
      let lineBuf = '';

      const logPath = join(task.directory, F_AGENT_LOG);
      // Append header with separator (don't truncate — preserve history across spawns)
      try { appendFileSync(logPath, `\n=== agent session started at ${new Date().toISOString()} ===\n`); } catch {}

      // Auto-generate autoresearch.sh — overwrites agent-modified versions on every spawn
      // Must NOT cd to another dir; runs from worktree root where node_modules lives
      try {
        writeFileSync(join(task.directory, 'autoresearch.sh'), [
          '#!/bin/bash',
          '# Auto-generated by orchestrator — do not cd to another directory',
          'DIR="$(cd "$(dirname "$0")" \&\& pwd)"',
          'node "$DIR/benchmark.js"',
        ].join('\n') + '\n');
      } catch {}

      const handleData = (txt: string) => {
        output += txt;
        try { appendFileSync(logPath, txt); } catch {}

        // Parse NDJSON lines in the stream for live console output
        lineBuf += txt;
        const lines = lineBuf.split('\n');
        /* c8 ignore next 1 — split always returns ≥1 element, pop never returns undefined */
        lineBuf = lines.pop() ?? '';
        for (const raw of lines) {
          if (!raw.trim()) continue;
          try {
            const obj = JSON.parse(raw);
            PiSpawner.#printEvent(obj);
          } catch { /* incomplete line — wait for more data */ }
        }
      };

      child.stdout?.on('data', (d: Buffer) => handleData(d.toString()));
      child.stderr?.on('data', (d: Buffer) => handleData(d.toString()));

      child.on('close', (code: number | null) => {
        const iterations = (output.match(/log_experiment/g) || []).length;
        // Append footer and close — previous chunks already streamed
        try {
          appendFileSync(logPath, `=== agent session ended (exit ${code}) ===
`);
        /* c8 ignore start */
        } catch (e: unknown) {
          console.error(`[PiSpawner] failed to finalize ${F_AGENT_LOG}: ${e instanceof Error ? e.message : String(e)}`);
        }
        /* c8 ignore stop */
        done({ success: code === 0, iterations });
      });

      child.on('error', () => {
        done({ success: false, iterations: 0 });
      });
    });
  }

  /** Print key agent events to console for live visibility */
  static #printEvent(obj: Record<string, unknown>): void {
    const t = String(obj.type ?? '');

    if (t === 'tool_execution_start') {
      const name = String(obj.toolName ?? obj.name ?? '');
      const args = obj.arguments ?? {};
      let summary = name;
      if (typeof args === 'object' && args && 'path' in args) {
        summary += ` ${String(args.path)}`;
      } else if (typeof args === 'object' && args && 'command' in args) {
        const cmd = String(args.command).slice(0, 80);
        summary += ` ${cmd}`;
      }
      console.log(`  🔧 ${summary}`);
    }

    if (t === 'tool_execution_end') {
      const name = String(obj.toolName ?? '');
      const result = obj.result as Record<string, unknown> | undefined;
      const content = result?.content;
      if (Array.isArray(content)) {
        for (const c of content) {
          if (typeof c === 'object' && c && c.type === 'text') {
            const text = String(c.text);
            // Show METRIC lines from run_experiment
            const metricM = text.match(/METRIC\s+\w+=(\d+(?:\.\d+)?)/);
            if (metricM) {
              console.log(`  📊 ${metricM[0]}`);
            }
            // Show log_experiment results
            if (name === 'log_experiment') {
              const line = text.split('\n')[0]?.trim();
              if (line) {
                const icon = line.includes('keep') ? '💾' : line.includes('crash') ? '💥' : '📝';
                console.log(`  ${icon} ${line.slice(0, 100)}`);
              }
            }
          }
        }
      }
      if (obj.isError) {
        console.log(`  ❌ ${name} failed`);
      }
    }
  }

  #prompt(task: TaskState, cwd: string): string {
    // Use relative paths — agent works in cwd, worktree mirrors main repo structure
    const arPath = task.directory.startsWith(cwd)
      ? task.directory.slice(cwd.length + 1) // relative from worktree root
      : task.directory;
    return [
      `You are an autonomous task agent. Working directory: ${cwd}.`,
      '',
      `Task: read ${arPath}/autoresearch.md, then run the experiment loop.`,
      `Use init_experiment, run_experiment (with ${arPath}/autoresearch.sh),`,
      `and log_experiment. Edit only files listed in the task's scope.`,
      'Iterate until metric=0 for 3 consecutive keep runs.',
      '',
      'NOTE: autoresearch.sh must NOT cd to another directory — it runs from the worktree',
      'root where node_modules and all source files are available.',
    ].join('\n');
  }
}
